import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import localFont from "next/font/local";

const fontMono = localFont({
  src: "font-mono.woff2",
  variable: "--font-mono",
});

const fontSansSerif = localFont({
  src: "font-sans-serif.otf",
  variable: "--font-sans-serif",
});

const fontSerif = localFont({
  src: "font-serif.woff2",
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontMono.variable} ${fontSansSerif.variable} ${fontSerif.variable}`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
